resources:
  - ./k8s/auth-depl.yaml
  - ./k8s/auth-mongo-depl.yaml
  - ./k8s/client-depl.yaml
  - ./k8s/rbmq-depl.yaml
  - ./k8s/tickets-depl.yaml
  - ./k8s/tickets-mongo-depl.yaml
  - ./k8s-dev/ingress-srv.yaml
