apiVersion: v1
kind: Service
metadata:
  name: rbmq-test-srv
spec:
  selector:
    app: rbmq-test
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rbmq-test
spec:
  selector:
    matchLabels:
      app: rbmq-test
  serviceName: "rbmq-test-srv"
  replicas: 1
  template:
    metadata:
      labels:
        app: rbmq-test
    spec:
      containers:
      - name: rs-rmq
        image: rabbitmq:management
        ports:
        - containerPort: 25672
        - containerPort: 5672
        - containerPort: 4369
        - containerPort: 15672