name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - run: cd tickets
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: https://hub.docker.com/repository/docker/thanhtruc123/auth
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thanhtruc123/tickets:latest
