name: Deploy-tickets

on:
  push:
    branches: [ master ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - run: |
        docker build ./tickets -t thanhtruc123/tickets:lastest
    - run: docker push thanhtruc123/tickets:lastest
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl rollout restart deployment tickets-depl


