name: Deploy-tickets
on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: login Docker hub
       uses: docker/login-action@v1
       with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS.TOKEN}}
        
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
       id: buildx 
      
     - name: Build and push
       uses: docker/build-push-action@v2
       with:
         context: ./auth/**
         file: Dockerfile
         builder: ${{steps.buildx.outputs.name}}
         push: true
         tag: ${{secrects.DOCKER_USERNAME}}/auth
