name: Deploy-auth

on:
  push:
    branches: [ master ]
    paths: 
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd auth && docker build -t thanhtruc123/auth .
    - name: Login to DockerHub Registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - run: docker push thanhtruc123/auth
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl rollout restart deployment auth-depl