name: Deploy-tickets

on:
  push:
    branches: [ master ]
    paths: 
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd tickets && docker build -t thanhtruc123/tickets .
    - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
       repository: ${{secrets.DOCKER_USERNAME}}/tickets
       tag_with_ref: true
       push: true
       tags: thanhtruc123/tickets:latest
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl rollout restart deployment tickets-depl
