# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy-auth

on:
  push:
    branches: [ master ]
    paths: 
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl apply -f infra/k8s && kubectl apply -f ./infra/k8s-prod
