name: deploy
on:
  push:
    branches: 
      - master
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t stephengrider/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME  }}
          DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD }}
