name: Deploy-auth

on:
  push:
    branches: [ master ]
    paths: 
      - 'tickets/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: publish docker
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./auth
          repository: thanhtruc123/auth
          tags: thanhtruc123/auth:lastest
          push: true
          path: ./auth      
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
        
