name: Deploy-tickets

on:
  push:
    branches: [ master ]
    paths: 
      - 'tickets/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: publish docker
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./tickets
          repository: thanhtruc123/tickets
          tags: thanhtruc123/tickets:lastest
          push: true
          path: ./tickets      
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
